# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-scratch',
                'doc_host': 'https://scathers.github.io',
                'git_url': 'https://github.com/scathers/nbdev-scratch',
                'lib_path': 'nbdev_scratch'},
  'syms': {'nbdev_scratch.core': {'nbdev_scratch.core.foo': ('core.html#foo', 'nbdev_scratch/core.py')}}}
